# Generated by Django 4.2.13 on 2024-06-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sub_title', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'HeaderText',
                'verbose_name_plural': 'HeaderText',
            },
        ),
        migrations.CreateModel(
            name='OG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('type', models.CharField(max_length=255)),
                ('image', models.ImageField(max_length=255, upload_to='')),
                ('urls', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Open Graph',
                'verbose_name_plural': 'Open Graphs',
            },
        ),
        migrations.CreateModel(
            name='SEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=500)),
                ('keywords', models.CharField(max_length=255)),
                ('robots', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'seo',
                'verbose_name_plural': 'seo',
            },
        ),
    ]
