# Generated by Django 4.2.13 on 2024-06-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headertext',
            old_name='sub_title',
            new_name='description',
        ),
    ]
