# Generated by Django 4.2.13 on 2024-06-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_sub_title_headertext_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='DinamicTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(max_length=255, verbose_name='Header Text')),
            ],
            options={
                'verbose_name': 'Dinamic Texts',
                'verbose_name_plural': 'Dinamic Texts',
            },
        ),
        migrations.RemoveField(
            model_name='seo',
            name='language',
        ),
        migrations.AlterField(
            model_name='headertext',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
