# Generated by Django 4.2.13 on 2024-06-25 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_dinamictexts_remove_seo_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinamictexts',
            name='header_text',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.headertext'),
        ),
    ]
