# Generated by Django 4.2.13 on 2024-06-25 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_dinamictexts_header_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinamictexts',
            name='header_text',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.headertext'),
        ),
    ]
