# Generated by Django 4.2.13 on 2024-06-25 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_dinamictexts_dynamictexts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamictexts',
            name='header_text',
        ),
        migrations.AddField(
            model_name='headertext',
            name='dynamic_text',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='header_text', to='app.dynamictexts'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='headertext',
            name='description',
            field=models.TextField(max_length=255),
        ),
    ]
