# Generated by Django 4.2.13 on 2024-06-25 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_dynamictexts_header_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footer_text', models.CharField(max_length=255)),
                ('dynamic_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_text', to='app.dynamictexts')),
            ],
            options={
                'verbose_name': 'FooterText',
                'verbose_name_plural': 'FooterText',
            },
        ),
    ]
