# Generated by Django 4.2.13 on 2024-06-27 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_footertext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footertext',
            name='dynamic_text',
        ),
        migrations.RemoveField(
            model_name='headertext',
            name='dynamic_text',
        ),
        migrations.DeleteModel(
            name='OG',
        ),
        migrations.DeleteModel(
            name='SEO',
        ),
        migrations.DeleteModel(
            name='DynamicTexts',
        ),
        migrations.DeleteModel(
            name='FooterText',
        ),
        migrations.DeleteModel(
            name='HeaderText',
        ),
    ]
