# Generated by Django 4.2.13 on 2024-06-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeBlocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='tree-blocks')),
            ],
            options={
                'verbose_name': 'Tree Block',
                'verbose_name_plural': 'Tree Blocks',
            },
        ),
        migrations.DeleteModel(
            name='HeTreeBlocks',
        ),
    ]
