# Generated by Django 4.2.13 on 2024-06-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_treeblocks_delete_hetreeblocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='left-block')),
            ],
            options={
                'verbose_name': 'Left Block',
                'verbose_name_plural': 'Left Block',
            },
        ),
        migrations.CreateModel(
            name='RightBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='right-block')),
            ],
            options={
                'verbose_name': 'Right Block',
                'verbose_name_plural': 'Right Block',
            },
        ),
    ]
