# Generated by Django 4.2.13 on 2024-06-29 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_leftblock_rightblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProcessMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
            ],
            options={
                'verbose_name': 'WorkProcess',
                'verbose_name_plural': 'WorkProcess',
            },
        ),
        migrations.CreateModel(
            name='WorkProcessChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='work_process')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childeren', to='app.workprocessmain')),
            ],
        ),
    ]
