# Generated by Django 4.2.13 on 2024-07-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_workprocessmain_workprocesschild'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(max_length=255)),
                ('image', models.ImageField(upload_to='work_process')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkProcessChild',
        ),
        migrations.DeleteModel(
            name='WorkProcessMain',
        ),
    ]
