# Generated by Django 4.2.13 on 2024-07-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_workprocess_delete_workprocesschild_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=400)),
                ('first_name', models.CharField(max_length=45)),
                ('Last_name', models.CharField(max_length=45)),
                ('position', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='reviews')),
            ],
        ),
    ]
