# Generated by Django 4.2.13 on 2024-07-05 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_reviews'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPlanMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Pricing Plan',
                'verbose_name_plural': 'Pricing Plans',
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('space', models.CharField(max_length=255)),
                ('transfer', models.CharField(max_length=255)),
                ('panel', models.CharField(max_length=255)),
                ('support', models.CharField(max_length=255)),
                ('emails', models.CharField(max_length=255)),
                ('securety', models.CharField(max_length=255)),
                ('fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pricingplanmain')),
            ],
        ),
    ]
