# Generated by Django 4.2.13 on 2024-07-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_pricingplanmain_pricingplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingplan',
            options={'verbose_name': 'Pricing Plan', 'verbose_name_plural': 'Pricing Plans'},
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='price',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
