# Generated by Django 4.2.13 on 2024-07-06 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_pricingplan_options_pricingplan_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingplanmain',
            name='title',
        ),
    ]
