# Generated by Django 4.2.13 on 2024-07-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_pricingplanmain_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingplan',
            name='fk',
        ),
        migrations.DeleteModel(
            name='PricingPlanMain',
        ),
    ]
