# Generated by Django 4.2.13 on 2024-07-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_remove_pricingplan_fk_delete_pricingplanmain'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects', models.IntegerField(default=0)),
                ('happy_clients', models.IntegerField(default=0)),
                ('award_wins', models.IntegerField(default=0)),
                ('countries', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Counter',
                'verbose_name_plural': 'Counters',
            },
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='is_emails',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='is_panel',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='is_security',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='is_space',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='is_support',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pricingplan',
            name='is_transfer',
            field=models.BooleanField(default=True),
        ),
    ]
