# Generated by Django 4.2.13 on 2024-07-06 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_counter_pricingplan_is_emails_pricingplan_is_panel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counter',
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name': 'Review', 'verbose_name_plural': 'Reviews'},
        ),
        migrations.AlterModelOptions(
            name='workprocess',
            options={'verbose_name': 'Work process', 'verbose_name_plural': 'Work process'},
        ),
    ]
