# Generated by Django 4.2.13 on 2024-07-06 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_delete_counter_alter_reviews_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricingplan',
            old_name='securety',
            new_name='security',
        ),
    ]
