# Generated by Django 4.2.13 on 2024-07-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_rename_securety_pricingplan_security'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projects', models.IntegerField(default=0)),
                ('happy_clients', models.IntegerField(default=0)),
                ('award_wins', models.IntegerField(default=0)),
                ('countries', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Counter',
                'verbose_name_plural': 'Counters',
            },
        ),
    ]
