# Generated by Django 4.2.13 on 2024-07-10 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMessage',
            new_name='Message',
        ),
    ]
